=pod

=head1 NAME

DBIx::Class::Manual::Contributing - How to get involved in DBIx::Class

=head1 CONTRIBUTORS

=head2 Verify the change you want to make with other users

To save yourself, and the DBIx::Class maintainers time, please take a
moment to verify your ideas with other DBIx::Class users. Use the IRC
channel (#dbix-class on irc.perl.org) or the mailing list L<> to get
quick feedback on the change you'd like to make. Your idea may already
be a work in progress you can help contribute to, and avoid
duplicating effort, or there may be a better way to solve your
problem.

=head2 Getting the latest content

DBIx::Class's source code is stored in a respoitory using the git
version control system(L<http://??.com>). To contribute patches,
whether code or for the documentation, please make sure you have a
copy of the latest content.

=head3 Using github.com

L<http://github.com> allows you to contribute to git based projects
using only your web browser. Use it ig you want to make casual/quick
contributions to documentation.

You can also use github to manage your forks of git based projects,
and contribute more complex patches (which require running tests).

=over

=item Create/Login to an account on gihub

Visit L<http://github.com> and create an account, or login to your existing account.

=item Visit the official DBIx::Class github repo, and fork it

L<http://github.com/dbsrgits/dbix-class> is the official DBIx::Class
repo, use the "Fork" button near the top right of the page to create
your own copy of the repo.

=item Make your changes in your local copy (Docs)

For pure documentation changes, you can now find the appropriate file
to change using the github interface, hit the "Edit" link and make the
required changes.

=item Make your changes (Code + tests)

To make code and test changes, you need to checkout the repository
content onto your own computer, so the tests can be run.

=over

=item * Linux / Unix systems

Run the "git clone" command passing it the url of your dbix-class fork, for example:

    git clone http://github.com/castaway/dbix-class 

This will create a directory "DBIx-Class" in your current directory,
and extract all the dbix-class code into it.

=item * Windows systems

??

=back

=item Once tested, notify the dbix-class maintainers of the changes

To submit changes back to the main DBIx::Class repository, use the
"Send pull request" button on the top right of your github.com
repository page.

Use the IRC channel or mailing list to keep up with the progress of your patch.

=back

=head2 Submitting simple documentation patches

=head3 For the CLI people

# make sure your name and email is set
# HACK HACK HACK
git commit -m 'foo'
git format-patch origin/master
# nopaste patches

=head3 For point-click people

Get a github account
make a fork of http://github.com/dbix-class/DBIx-Class
in your fork, go to the file, and click edit at the top right of the file viewer
Commit your changes with the button at the bottom
Paste a link in IRC or do a pull request (preferably the former)

=head2 Bigger features

# make a fork on github or gitorious or whatever and branch off of master

# HACK HACK HACK
git commit -m 'foo'

git rebase --root --onto sc/master
# get rid of useless commits and take out warns, commented out code, fixup commit messages, etc
git rebase --root --onto sc/master -i
git push gh
# pull request


=head1 MAINTAINERS

=head2 Simple documentation patches

# download patch
git am patchfile
# do the following if the user didn't
git --amend -m $revised_commit_mesg --author 'Firstname Lastname <email>'

=head2 Bigger features

git co master
git co -b remote-thingy
git pull git://github.com/frew/DBIx-Class.git branch
git log -p
# rebase to clean up history if need be
git co master
git merge remote-thingy

=head2 Releases

ensure Changes is up to date
set Changes version and timestamp
bump version in DBIx/Class.pm
git add lib/DBIx/Class.pm Changes
git ci -m 'release $version'
git tag v$version -m '$version tag'
perl Makefile.PL
make manifest
make disttest
make dist
make upload
bump version in DBIx/Class.pm to include _01 for master users

=head2 Syncronize with other mirrors

git clone git://git.shadowcat.co.uk/dbsrgits/DBIx-Class.git --mirror
cd DBIx-Class.git
git remote add github git@github.com:dbix-class/DBIx-Class.git

git fetch --tags --prune origin
git fetch --prune origin
git push --all github
